// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestNode(arg1) {
  return window['go']['main']['App']['TestNode'](arg1);
}

export function ToggleNodeStatus(arg1, arg2) {
  return window['go']['main']['App']['ToggleNodeStatus'](arg1, arg2);
}
