// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddNode(arg1:string):Promise<main.GASNodeModel>;

export function DeleteNode(arg1:string):Promise<void>;

export function GetNodes():Promise<Array<main.GASNodeModel>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function GetSettings():Promise<main.SettingsModel>;

export function SaveSettings(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestNode(arg1:string):Promise<main.ValidationResult>;

export function ToggleNodeStatus(arg1:string,arg2:string):Promise<void>;
